=== gsdlab/clafer/test/ClaferIR.xsd
<!-- ........................................................................ *
  *   Clafer Project                                                          *
  *   http://clafer.org                                                       *
  *                                                                           *
  *   File description: XML schema of Clafer intermediate representation (IR) *
  *   Depends on: Haskell IR data types defined for clafer                    *
  *   Author: Leonardo Passos <lpassos@gsd.uwaterloo.ca>                      *
  *   Contributors: Jimmy Liang <jliang@gsd.uwaterloo.ca>                     *
  *   Date: October 19th, 2011                                                *
  *   Last update: April 16th, 2012                                           *
  *                                                                           *
  *   Generate scala classes with:                                            *
  *   scalaxb -p gsd.clafer.ir ClaferIR.xsd                                   *
  *           - -protocol-file ClaferIR_XmlProtocol.scala                     *
  * ......................................................................... *
  */
-->
<xs:schema targetNamespace="http://clafer.org/ir"
           elementFormDefault="qualified"
           xmlns="http://clafer.org/ir"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cl="http://clafer.org/ir">

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!--
    data IType = TBoolean
                 | TString
                 | TInteger
                 | TReal
                 | TClafer
  -->
  <xs:complexType name="IType" abstract="true"/>
  <xs:element name="Type" type="cl:IType"/>

  <xs:complexType name="IBoolean">
      <xs:complexContent>
          <xs:extension base="cl:IType"/>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IString">
      <xs:complexContent>
          <xs:extension base="cl:IType"/>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IInteger">
      <xs:complexContent>
          <xs:extension base="cl:IType"/>
      </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="IReal">
      <xs:complexContent>
          <xs:extension base="cl:IType"/>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ISet">
      <xs:complexContent>
          <xs:extension base="cl:IType"/>
      </xs:complexContent>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data IModule = IModule {
      mName :: String,
      mDecls :: [IElement]
    }
  -->

  <xs:complexType name="IModule">
      <xs:sequence>
          <xs:element name="Name" type="xs:string"/>
          <xs:element ref="Declaration" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
  </xs:complexType>

  <xs:element name="Module" type="cl:IModule"/>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data IClafer =
       IClafer {
          isAbstract :: Bool,     - determines whether it's abstract
          gcard :: Maybe IGCard,  - group cardinality
          ident :: String,        - name
          uid :: String,          - (o) unique identifier
          super:: ISuper,         - superclafers
          card :: Maybe Interval, - cardinality
          glCard :: Interval,     - (o) global cardinality
          elements :: [IElement]  - subclafers or constraints specified in the context of given clafer
        }
  -->
  <xs:complexType name="IClafer">
      <xs:complexContent>
          <xs:extension base="IElement">
            <xs:sequence>
                <xs:element name="Position">
                  <xs:complexType>
                      <xs:sequence>
                          <xs:element name="Start">
                              <xs:complexType>
                                  <xs:sequence>
                                      <xs:element ref="IntLiteral" minOccurs="2" maxOccurs="2"/>
                                  </xs:sequence>
                              </xs:complexType>
                          </xs:element>
                          <xs:element name="End">
                              <xs:complexType>
                                  <xs:sequence>
                                      <xs:element ref="IntLiteral" minOccurs="2" maxOccurs="2"/>
                                  </xs:sequence>
                              </xs:complexType>
                          </xs:element>
                      </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="IsAbstract" type="xs:boolean"/>
                <xs:element name="GroupCard"  type="cl:IGroupCard" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Id"         type="xs:string"/>
                <xs:element name="UniqueId"   type="xs:string"/>
                <xs:element name="Supers"     type="cl:ISuper"/>
                <xs:element name="Card"       type="cl:IInterval" minOccurs="0" maxOccurs="1"/>
                <xs:element name="GlobalCard" type="cl:IInterval"/>
                <xs:element ref="Declaration" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data IElement =
       IEClafer IClafer
     | IEConstraint {
          isHard :: Bool,
          cpexp :: PExp
        }
     | IEGoal {
       isMaximize :: Bool,
       cpexp :: PExp
       }
   -->

  <xs:complexType name="IElement" abstract="true"/>
  <xs:element name="Declaration" type="IElement"/>

  <!-- No need to create IEClafer type. IClafer is already a subtype
       of IElement
    -->

  <xs:complexType name="IConstraint">
    <xs:complexContent>
      <xs:extension base="cl:IElement">
          <xs:sequence>
              <xs:element name="IsHard"    type="xs:boolean"/>
              <xs:element name="ParentExp" type="cl:IParentExp"/>
          </xs:sequence>
      </xs:extension>

    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IGoal">
    <xs:complexContent>
      <xs:extension base="cl:IElement">
          <xs:sequence>
              <xs:element name="IsMaximize"    type="xs:boolean"/>
              <xs:element name="ParentExp" type="cl:IParentExp"/>
          </xs:sequence>
      </xs:extension>

    </xs:complexContent>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data ISuper =
       ISuper {
          isOverlapping :: Bool,
          supers :: [PExp]
        }
  -->
  <xs:complexType name="ISuper">
    <xs:sequence>
        <xs:element name="IsOverlapping" type="xs:boolean"/>
        <xs:element name="Super"         type="cl:IParentExp" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data IGCard =
      IGCard {
          isKeyword :: Bool,
          interval :: Interval
        }
  -->

  <xs:complexType name="IGroupCard">
    <xs:sequence>
        <xs:element name="IsKeyword" type="xs:boolean"/>
        <xs:element name="Interval"  type="cl:IInterval"/>
    </xs:sequence>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- type Interval = (Integer, ExInteger) -->

  <xs:complexType name="IInterval">
      <xs:sequence>
          <xs:element name="Min">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="IntLiteral"/>
                </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Max">
            <xs:complexType>
                <xs:sequence>
                    <xs:element ref="IntLiteral"/>
                </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
  </xs:complexType>

  <!-- . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .-->
  <!-- data PExp = PExp {
      iType :: Maybe IType,
      pid :: String,
      exp :: IExp
    }
  -->

  <xs:complexType name="IParentExp">
      <xs:sequence>
          <xs:element name="Type"     type="cl:IType" minOccurs="0" maxOccurs="1"/>
          <xs:element name="ParentId" type="xs:string" minOccurs="0" maxOccurs="1"/>
          <xs:element name="Position">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="Start">
                          <xs:complexType>
                              <xs:sequence>
                                  <xs:element ref="IntLiteral" minOccurs="2" maxOccurs="2"/>
                              </xs:sequence>
                          </xs:complexType>
                      </xs:element>
                      <xs:element name="End">
                          <xs:complexType>
                              <xs:sequence>
                                  <xs:element ref="IntLiteral" minOccurs="2" maxOccurs="2"/>
                              </xs:sequence>
                          </xs:complexType>
                      </xs:element>
                  </xs:sequence>
              </xs:complexType>
          </xs:element>
          <xs:element name="Exp"      type="cl:IExp"/>
      </xs:sequence>
  </xs:complexType>


  <!-- ......................................................................-->
  <!--
    data IExp =
       - quantified expression  declarations
       IDeclPExp {quant :: IQuant, oDecls :: [IDecl], bpexp :: PExp}
     | IFunExp {op :: String, exps :: [PExp]}
     | IInt Integer                  - integer number
     | IDouble Double                - real number
     | IStr String                   - string
     | IClaferId {                   - clafer name
          modName :: String,         - module name
          sident :: String,          - name
          isTop :: Bool              - identifier refers to a top-level definition
        }
   -->
  <xs:complexType name="IExp" abstract="true"/>

  <xs:complexType name="IDeclarationParentExp">
      <xs:complexContent>
          <xs:extension base="cl:IExp">
              <xs:sequence>
                  <xs:element name="Quantifier"    type="cl:IQuantifier"/>
                  <xs:element name="Declaration"   type="cl:IDeclaration" minOccurs="0" maxOccurs="unbounded"/>
                  <xs:element name="BodyParentExp" type="cl:IParentExp"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IFunctionExp">
      <xs:complexContent>
          <xs:extension base="IExp">
              <xs:sequence>
                  <xs:element name="Operation" type="xs:string"/>
                  <xs:element name="Argument" minOccurs="0" maxOccurs="unbounded" type="IParentExp"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IIntExp">
      <xs:complexContent>
          <xs:extension base="IExp">
              <xs:sequence>
                 <xs:element ref="IntLiteral"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IDoubleExp">
      <xs:complexContent>
          <xs:extension base="IExp">
              <xs:sequence>
                 <xs:element ref="DoubleLiteral"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IStringExp">
      <xs:complexContent>
          <xs:extension base="IExp">
              <xs:sequence>
                 <xs:element ref="StringLiteral"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>


  <xs:complexType name="IClaferId">
      <xs:complexContent>
          <xs:extension base="IExp">
              <xs:sequence>
                  <xs:element name="ModuleName" type="xs:string" minOccurs="0" maxOccurs="1"/>
                  <xs:element name="Id"         type="xs:string" />
                  <xs:element name="IsTop"      type="xs:boolean"/>
              </xs:sequence>
          </xs:extension>
      </xs:complexContent>
  </xs:complexType>

  <!-- ......................................................................-->
  <!-- data IDecl =
       IDecl {
          isDisj :: Bool,     - is disjunct
          decls :: [String],  - a list of local names
          body :: PExp        - set to which local names refer to
        }
    -->

   <xs:complexType name="IDeclaration">
       <xs:sequence>
           <xs:element name="IsDisjunct"       type="xs:boolean"/>
           <xs:element name="LocalDeclaration" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
           <xs:element name="Body"             type="cl:IParentExp"/>
       </xs:sequence>
   </xs:complexType>

  <!-- ......................................................................-->
  <!-- data IQuant =
        INo
        | ILone
        | IOne
        | ISome
        | IAll
   -->

   <xs:complexType name="IQuantifier" abstract="true"/>

   <xs:complexType name="INo">
       <xs:complexContent>
           <xs:extension base="cl:IQuantifier"/>
       </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="ILone">
       <xs:complexContent>
           <xs:extension base="cl:IQuantifier"/>
       </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="IOne">
       <xs:complexContent>
           <xs:extension base="cl:IQuantifier"/>
       </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="ISome">
       <xs:complexContent>
           <xs:extension base="cl:IQuantifier"/>
       </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="IAll">
       <xs:complexContent>
           <xs:extension base="cl:IQuantifier"/>
       </xs:complexContent>
   </xs:complexType>

 <!-- ......................................................................-->

 <xs:element name="IntLiteral"    type="xs:integer"/>
 <xs:element name="DoubleLiteral" type="xs:double"/>
 <xs:element name="StringLiteral" type="xs:string"/>

</xs:schema>

=== gsdlab/clafer/test/positive/test_neg_typesystem.xml
<?xml version="1.0"?><Module xmlns="http://clafer.org/ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cl="http://clafer.org/ir" xsi:schemaLocation="http://clafer.org/ir https://github.com/gsdlab/clafer/blob/master/src/ClaferIR.xsd"><Name></Name>
<Declaration xsi:type="cl:IClafer"><Position><Start><IntLiteral>1</IntLiteral>
<IntLiteral>1</IntLiteral>
</Start>
<End><IntLiteral>2</IntLiteral>
<IntLiteral>31</IntLiteral>
</End>
</Position>
<IsAbstract>true</IsAbstract>
<GroupCard><IsKeyword>false</IsKeyword>
<Interval><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</Interval>
</GroupCard>
<Id>Measurable</Id>
<UniqueId>c1_Measurable</UniqueId>
<Supers><IsOverlapping>false</IsOverlapping>
<Super><Type xsi:type="cl:ISet" /><ParentId></ParentId>
<Position><Start><IntLiteral>0</IntLiteral>
<IntLiteral>0</IntLiteral>
</Start>
<End><IntLiteral>0</IntLiteral>
<IntLiteral>0</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>clafer</Id>
<IsTop>false</IsTop>
</Exp></Super>
</Supers>
<Card><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</Card>
<GlobalCard><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</GlobalCard>
<Declaration xsi:type="cl:IClafer"><Position><Start><IntLiteral>2</IntLiteral>
<IntLiteral>10</IntLiteral>
</Start>
<End><IntLiteral>2</IntLiteral>
<IntLiteral>31</IntLiteral>
</End>
</Position>
<IsAbstract>false</IsAbstract>
<GroupCard><IsKeyword>false</IsKeyword>
<Interval><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</Interval>
</GroupCard>
<Id>performance</Id>
<UniqueId>c2_performance</UniqueId>
<Supers><IsOverlapping>false</IsOverlapping>
<Super><ParentId>integer_((2,24),(2,31))</ParentId>
<Position><Start><IntLiteral>2</IntLiteral>
<IntLiteral>24</IntLiteral>
</Start>
<End><IntLiteral>2</IntLiteral>
<IntLiteral>31</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>integer</Id>
<IsTop>true</IsTop>
</Exp></Super>
</Supers>
<Card><Min><IntLiteral>1</IntLiteral>
</Min>
<Max><IntLiteral>1</IntLiteral>
</Max>
</Card>
<GlobalCard><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</GlobalCard>
</Declaration></Declaration><Declaration xsi:type="cl:IClafer"><Position><Start><IntLiteral>4</IntLiteral>
<IntLiteral>1</IntLiteral>
</Start>
<End><IntLiteral>4</IntLiteral>
<IntLiteral>14</IntLiteral>
</End>
</Position>
<IsAbstract>false</IsAbstract>
<GroupCard><IsKeyword>false</IsKeyword>
<Interval><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</Interval>
</GroupCard>
<Id>D</Id>
<UniqueId>c3_D</UniqueId>
<Supers><IsOverlapping>false</IsOverlapping>
<Super><Type xsi:type="cl:ISet" /><ParentId>Measurable_((4,4),(4,14))</ParentId>
<Position><Start><IntLiteral>4</IntLiteral>
<IntLiteral>4</IntLiteral>
</Start>
<End><IntLiteral>4</IntLiteral>
<IntLiteral>14</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c1_Measurable</Id>
<IsTop>true</IsTop>
</Exp></Super>
</Supers>
<Card><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>1</IntLiteral>
</Max>
</Card>
<GlobalCard><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>1</IntLiteral>
</Max>
</GlobalCard>
</Declaration><Declaration xsi:type="cl:IClafer"><Position><Start><IntLiteral>6</IntLiteral>
<IntLiteral>1</IntLiteral>
</Start>
<End><IntLiteral>6</IntLiteral>
<IntLiteral>13</IntLiteral>
</End>
</Position>
<IsAbstract>false</IsAbstract>
<GroupCard><IsKeyword>false</IsKeyword>
<Interval><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>-1</IntLiteral>
</Max>
</Interval>
</GroupCard>
<Id>C</Id>
<UniqueId>c4_C</UniqueId>
<Supers><IsOverlapping>false</IsOverlapping>
<Super><Type xsi:type="cl:ISet" /><ParentId>Measurable_((6,3),(6,13))</ParentId>
<Position><Start><IntLiteral>6</IntLiteral>
<IntLiteral>3</IntLiteral>
</Start>
<End><IntLiteral>6</IntLiteral>
<IntLiteral>13</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c1_Measurable</Id>
<IsTop>true</IsTop>
</Exp></Super>
</Supers>
<Card><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>1</IntLiteral>
</Max>
</Card>
<GlobalCard><Min><IntLiteral>0</IntLiteral>
</Min>
<Max><IntLiteral>1</IntLiteral>
</Max>
</GlobalCard>
</Declaration><Declaration xsi:type="cl:IConstraint"><IsHard>true</IsHard>
<ParentExp><Type xsi:type="cl:IBoolean" /><ParentId>c5_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>3</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>=</Operation>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>c6_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>3</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>16</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>.</Operation>
<Argument><Type xsi:type="cl:ISet" /><ParentId>c7_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>3</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>4</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c4_C</Id>
<IsTop>true</IsTop>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>._((8,5),(8,16))</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>5</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>16</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>.</Operation>
<Argument><Type xsi:type="cl:ISet" /><ParentId>c8_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>5</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>16</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c2_performance</Id>
<IsTop>false</IsTop>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>ref_((8,5),(8,16))</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>5</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>16</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>ref</Id>
<IsTop>false</IsTop>
</Exp></Argument>
</Exp></Argument>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>c9_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>19</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>*</Operation>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>c10_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>19</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IIntExp"><IntLiteral>-1</IntLiteral>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>c11_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>20</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>.</Operation>
<Argument><Type xsi:type="cl:ISet" /><ParentId>c12_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>20</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>21</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c3_D</Id>
<IsTop>true</IsTop>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>._((8,22),(8,33))</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>22</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IFunctionExp"><Operation>.</Operation>
<Argument><Type xsi:type="cl:ISet" /><ParentId>c13_exp</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>22</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>c2_performance</Id>
<IsTop>false</IsTop>
</Exp></Argument>
<Argument><Type xsi:type="cl:IInteger" /><ParentId>ref_((8,22),(8,33))</ParentId>
<Position><Start><IntLiteral>8</IntLiteral>
<IntLiteral>22</IntLiteral>
</Start>
<End><IntLiteral>8</IntLiteral>
<IntLiteral>33</IntLiteral>
</End>
</Position>
<Exp xsi:type="cl:IClaferId"><ModuleName></ModuleName>
<Id>ref</Id>
<IsTop>false</IsTop>
</Exp></Argument>
</Exp></Argument>
</Exp></Argument>
</Exp></Argument>
</Exp></ParentExp>
</Declaration></Module>
