=== gsdlab/clafer/test/experimental/i105-instance-data-notation/i105-instance-data.xsd
<?xml version="1.0"?>
<!--
abstract A
    b ?
    c *
    d -> A *
    f -> integer ?

A1 : A
    [ b ]
    [ no c ]
    [ no d ]
    [ f = 5 ]

A2 : A
    [ no b ]
    [ #c = 2 ]
    [ no d ]
    [ f ]

A3 : A
    [ b ]
    [ one c ]
    [ d = A1, A2 ]
    [ no f ]
/-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://clafer.org/data"
  xmlns="http://clafer.org/data"
  elementFormDefault="qualified">

<xs:complexType name="A" id="c1_A" abstract="true">
  <xs:sequence>
    <xs:element name="b" type="b" minOccurs="0" />
    <xs:element name="c" type="c" minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="d" type="d" minOccurs="0" maxOccurs="unbounded"/>
	<xs:element name="f" type="f" minOccurs="0" maxOccurs="1"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:complexType name="b" id="c2_b">
  <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:complexType name="c" id="c3_c">
  <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:complexType name="d" id="c4_d">
  <xs:sequence>
    <xs:element name="ref" type="xs:string"/>
  </xs:sequence>
  <xs:attribute name="id" type="xs:string"/>
</xs:complexType>

<xs:complexType name="f" id="c14_f">
  <xs:simpleContent>
    <xs:extension base="xs:integer">
      <xs:attribute name="id" type="xs:string"/>
	</xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="A1" id="c15_A1">
  <xs:complexContent>
    <xs:extension base="A" />
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="A2" id="c25_A2">
  <xs:complexContent>
    <xs:extension base="A" />
  </xs:complexContent>
</xs:complexType>

<xs:complexType name="A3" id="c36_A3">
  <xs:complexContent>
    <xs:extension base="A" />
  </xs:complexContent>
</xs:complexType>

<xs:element name="data">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="A1" type="A1"/>
      <xs:element name="A2" type="A2"/>
	  <xs:element name="A3" type="A3"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== gsdlab/clafer/test/experimental/i105-instance-data-notation/i105-instance-data.xml
<?xml version="1.0"?>
<!--
A1 : A
    b1 : b
    f1 : integer = 5

A2 : A
    c1 : c
    c2 : c
    f2 : integer = 7

A3 : A
    b2 : b
    c3 : c
    d1 : d = A1
    d2 : d = A2
/-->
<data
xmlns="http://clafer.org/data"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://clafer.org/data i105-instance-data.xsd">
  <A1 id="A1">
    <b id="b1"/>
	<f id="f1">5</f>
  </A1>
  <A2 id="A2">
    <c id="c1"/>
	<c id="c2"/>
	<f id="f2">5</f>
  </A2>
  <A3 id="A3">
    <b id="b2"/>
    <c id="c3"/>	
	<d id="d1"><ref>A1</ref></d>	
	<d id="d2"><ref>A2</ref></d>		
  </A3>
</data>
